In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
warnings.filterwarnings("ignore")

In [4]:
combat = pd.read_csv('combats.csv')
pokemon = pd.read_csv('pokemon.csv')

In [5]:
pokemon.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

### Data Transformation

In [6]:
pokemon.rename(columns={'#':'id', 'Name':'name', 'Type 1':'t1', 'Type 2':'t2', 
                        'HP':'hp', 'Attack':'attack', 'Defense':'defense', 'Sp. Atk':'spatk', 
                        'Sp. Def':'spdef', 'Speed':'speed', 'Legendary':'legendary'}, inplace = True)
pokemon.drop(['Generation'], axis = 1, inplace=True)
pokemon['legendary'] = pokemon['legendary'].replace([True,False],[1,0])

In [7]:
pokemon[['hp', 'attack', 'defense', 'spatk', 'spdef', 'speed']] = \
pokemon[['hp', 'attack', 'defense', 'spatk', 'spdef', 'speed']].astype(float)

In [8]:
print('Distinct values: {}'.format(len(pokemon['t1'].unique())))
print('Distinct values: {}'.format(len(pokemon['t2'].unique())))

Distinct values: 18
Distinct values: 19

In [9]:
print('t1: {}'.format(pokemon['t1'].unique()))
print('t2: {}'.format(pokemon['t2'].unique()))

t1: ['Grass' 'Fire' 'Water' 'Bug' 'Normal' 'Poison' 'Electric' 'Ground'
 'Fairy' 'Fighting' 'Psychic' 'Rock' 'Ghost' 'Ice' 'Dragon' 'Dark' 'Steel'
 'Flying']
t2: ['Poison' nan 'Flying' 'Dragon' 'Ground' 'Fairy' 'Grass' 'Fighting'
 'Psychic' 'Steel' 'Ice' 'Rock' 'Dark' 'Water' 'Electric' 'Fire' 'Ghost'
 'Bug' 'Normal']

### Import Pokemon Attribute

<img src='https://upload.wikimedia.org/wikipedia/commons/9/97/Pokemon_Type_Chart.svg', align='left'>

In [10]:
dic_physical = {'Normal', 'Fighting', 'Flying', 'Poison', 'Ground', 'Rock', 'Ghost', 'Bug', 'Steel'}
dic_special = {'Water', 'Fire', 'Grass', 'Electric', 'Psychic', 'Ice', 'Dragon', 'Dark', 'Fairy'}

In [11]:
Normal = {"Normal": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Bug": 1, "Rock": 0.5, "Ghost": 0, "Steel": 0.5, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Psychic": 1, "Dragon": 1, "Dark": 1, "Fairy": 1}
Fighting = {"Normal": 2, "Fighting": 1, "Poison": 0.5, "Ground": 1, "Flying": 0.5, "Bug": 0.5, "Rock": 2, "Ghost": 0, "Steel": 2, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 2, "Psychic": 0.5, "Dragon": 1, "Dark": 2, "Fairy": 0.5}
Poison = {"Normal": 1, "Fighting": 1, "Poison": 0.5, "Ground": 0.5, "Flying": 1, "Bug": 1, "Rock": 0.5, "Ghost": 0.5, "Steel": 0, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 2, "Ice": 1, "Psychic": 1, "Dragon": 1, "Dark": 1, "Fairy": 2}
Ground = {"Normal": 1, "Fighting": 1, "Poison": 2, "Ground": 1, "Flying": 0, "Bug": 0.5, "Rock": 2, "Ghost": 1, "Steel": 2, "Fire": 2, "Water": 1, "Electric": 2, "Grass": 0.5, "Ice": 1, "Psychic": 1, "Dragon": 1, "Dark": 1, "Fairy": 1}
Flying = {"Normal": 1, "Fighting": 2, "Poison": 1, "Ground": 1, "Flying": 1, "Bug": 2, "Rock": 0.5, "Ghost": 1, "Steel": 0.5, "Fire": 1, "Water": 1, "Electric": 0.5, "Grass": 2, "Ice": 1, "Psychic": 1, "Dragon": 1, "Dark": 1, "Fairy": 1}
Bug = {"Normal": 1, "Fighting": 0.5, "Poison": 0.5, "Ground": 1, "Flying": 0.5, "Bug": 1, "Rock": 1, "Ghost": 0.5, "Steel": 0.5, "Fire": 0.5, "Water": 1, "Electric": 1, "Grass": 2, "Ice": 1, "Psychic": 2, "Dragon": 1, "Dark": 2, "Fairy": 0.5}
Rock = {"Normal": 1, "Fighting": 0.5, "Poison": 1, "Ground": 0.5, "Flying": 2, "Bug": 2, "Rock": 1, "Ghost": 1, "Steel": 0.5, "Fire": 2, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 2, "Psychic": 1, "Dragon": 1, "Dark": 1, "Fairy": 1}
Ghost = {"Normal": 0, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Bug": 1, "Rock": 1, "Ghost": 2, "Steel": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Psychic": 2, "Dragon": 1, "Dark": 0.5, "Fairy": 1}
Steel = {"Normal": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Bug": 1, "Rock": 2, "Ghost": 1, "Steel": 0.5, "Fire": 0.5, "Water": 0.5, "Electric": 0.5, "Grass": 1, "Ice": 2, "Psychic": 1, "Dragon": 1, "Dark": 1, "Fairy": 0.5}
Fire = {"Normal": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Bug": 2, "Rock": 0.5, "Ghost": 1, "Steel": 2, "Fire": 0.5, "Water": 0.5, "Electric": 1, "Grass": 2, "Ice": 2, "Psychic": 1, "Dragon": 0.5, "Dark": 1, "Fairy": 1}
Water = {"Normal": 1, "Fighting": 1, "Poison": 1, "Ground": 2, "Flying": 1, "Bug": 1, "Rock": 2, "Ghost": 1, "Steel": 1, "Fire": 2, "Water": 0.5, "Electric": 1, "Grass": 0.5, "Ice": 1, "Psychic": 1, "Dragon": 0.5, "Dark": 1, "Fairy": 1}
Electric = {"Normal": 1, "Fighting": 1, "Poison": 1, "Ground": 0, "Flying": 2, "Bug": 1, "Rock": 1, "Ghost": 1, "Steel": 1, "Fire": 1, "Water": 2, "Electric": 0.5, "Grass": 0.5, "Ice": 1, "Psychic": 1, "Dragon": 0.5, "Dark": 1, "Fairy": 1}
Grass = {"Normal": 1, "Fighting": 1, "Poison": 0.5, "Ground": 2, "Flying": 0.5, "Bug": 0.5, "Rock": 2, "Ghost": 1, "Steel": 0.5, "Fire": 0.5, "Water": 2, "Electric": 1, "Grass": 0.5, "Ice": 1, "Psychic": 1, "Dragon": 0.5, "Dark": 1, "Fairy": 1}
Ice = {"Normal": 1, "Fighting": 1, "Poison": 1, "Ground": 2, "Flying": 2, "Bug": 1, "Rock": 1, "Ghost": 1, "Steel": 0.5, "Fire": 0.5, "Water": 0.5, "Electric": 1, "Grass": 2, "Ice": 0.5, "Psychic": 1, "Dragon": 2, "Dark": 1, "Fairy": 1}
Psychic = {"Normal": 1, "Fighting": 1, "Poison": 2, "Ground": 2, "Flying": 1, "Bug": 1, "Rock": 1, "Ghost": 1, "Steel": 0.5, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Psychic": 0.5, "Dragon": 1, "Dark": 0, "Fairy": 1}
Dragon = {"Normal": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Bug": 1, "Rock": 1, "Ghost": 1, "Steel": 0.5, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Psychic": 1, "Dragon": 2, "Dark": 1, "Fairy": 0}
Dark = {"Normal": 1, "Fighting": 0.5, "Poison": 1, "Ground": 1, "Flying": 1, "Bug": 1, "Rock": 1, "Ghost": 2, "Steel": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Psychic": 2, "Dragon": 1, "Dark": 0.5, "Fairy": 0.5}
Fairy = {"Normal": 1, "Fighting": 2, "Poison": 0.5, "Ground": 1, "Flying": 1, "Bug": 1, "Rock": 1, "Ghost": 1, "Steel": 0.5, "Fire": 0.5, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Psychic": 1, "Dragon": 2, "Dark": 2, "Fairy": 1}
type_relation = {"Normal": Normal, "Fighting": Fighting, "Poison": Poison, "Ground": Ground, "Flying": Flying, "Bug": Bug, "Rock": Rock, "Ghost": Ghost, "Steel": Steel, "Fire": Fire, "Water": Water, "Electric": Electric, "Grass": Grass, "Ice": Ice, "Psychic": Psychic, "Dragon": Dragon, "Dark": Dark, "Fairy": Fairy}

In [12]:
df_type = pd.DataFrame(type_relation).T
df_type

,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
Bug,1.0,2.0,1.0,1.0,0.5,0.5,0.5,0.5,0.5,2.0,1.0,1.0,1.0,0.5,2.0,1.0,0.5,1.0
Dark,1.0,0.5,1.0,1.0,0.5,0.5,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0
Dragon,1.0,1.0,2.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
Electric,1.0,1.0,0.5,0.5,1.0,1.0,1.0,2.0,1.0,0.5,0.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0
Fairy,1.0,2.0,2.0,1.0,1.0,2.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,0.5,1.0
Fighting,0.5,2.0,1.0,1.0,0.5,1.0,1.0,0.5,0.0,1.0,1.0,2.0,2.0,0.5,0.5,2.0,2.0,1.0
Fire,2.0,1.0,0.5,1.0,1.0,1.0,0.5,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,0.5,2.0,0.5
Flying,2.0,1.0,1.0,0.5,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,0.5,0.5,1.0
Ghost,1.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,0.0,1.0,2.0,1.0,1.0,1.0
Grass,0.5,1.0,0.5,1.0,1.0,1.0,0.5,0.5,1.0,0.5,2.0,1.0,1.0,0.5,1.0,2.0,0.5,2.0
Ground,0.5,1.0,1.0,2.0,1.0,1.0,2.0,0.0,1.0,0.5,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0
Ice,1.0,1.0,2.0,1.0,1.0,1.0,0.5,2.0,1.0,2.0,2.0,0.5,1.0,1.0,1.0,1.0,0.5,0.5
Normal,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.5,1.0
Poison,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,0.5,2.0,0.5,1.0,1.0,0.5,1.0,0.5,0.0,1.0
Psychic,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,0.5,1.0,0.5,1.0
Rock,2.0,1.0,1.0,1.0,1.0,0.5,2.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,1.0,0.5,1.0
Steel,1.0,1.0,1.0,0.5,0.5,1.0,0.5,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,0.5,0.5
Water,1.0,1.0,0.5,1.0,1.0,1.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,1.0,2.0,1.0,0.5

### Validate the combats data

In [13]:
print('Number of invalid row:', len([x[2] for idx,x in combat.iterrows() if x[2] != x[0] and x[2] != x[1]]))

Number of invalid row: 0

### Featuring Engineering

In [14]:
def createNewEffDF(pokemon,combat,df_type):
    atk_eff, spatk_eff = [], []
    for i in range(combat.shape[0]):
        #use values[0] to transform to DF easily
        t11_atk, t11_spatk, t12_atk, t12_spatk = -1, -1, -1, -1
        attack = pokemon[pokemon.id == combat.iloc[i,0]]['attack'].values[0]
        spatk = pokemon[pokemon.id == combat.iloc[i,0]]['spatk'].values[0]
        defense = pokemon[pokemon.id == combat.iloc[i,1]]['defense'].values[0]
        spdef = pokemon[pokemon.id == combat.iloc[i,1]]['spdef'].values[0]
        t11 = pokemon[pokemon.id == combat.iloc[i,0]]['t1'].values[0]
        t21 = pokemon[pokemon.id == combat.iloc[i,1]]['t1'].values[0]
        eff_atk = df_type.loc[t11][t21]
        if t11 in dic_physical: #belongs to physical attack
            t11_atk = attack * eff_atk  
        else:                   #belongs to special attack
            t11_spatk = spatk * eff_atk
        #t12 is not NaN
        if not pokemon[pokemon.id == combat.iloc[i,0]]['t2'].isna().values[0]:
            t12 = pokemon[pokemon.id == combat.iloc[i,0]]['t2'].values[0]
            if not pokemon[pokemon.id == combat.iloc[i,1]]['t2'].isna().values[0]:
                t22 = pokemon.loc[pokemon.id == combat.iloc[i,1]]['t2'].values[0]
                if t11_atk != -1:
                    t11_atk *= df_type.loc[t11][t22]
                else:
                    t11_spatk *= df_type.loc[t11][t22]
                if t12 in dic_physical:
                    t12_atk = attack * df_type.loc[t12][t21] * df_type.loc[t12][t22]
                else:
                    t12_spatk = spatk * df_type.loc[t12][t21] * df_type.loc[t12][t22]
            else:
                if t12 in dic_physical:
                    t12_atk = attack * df_type.loc[t12][t21]
                else:
                    t12_spatk = spatk * df_type.loc[t12][t21]          
        else:
            if not pokemon[pokemon.id == combat.iloc[i,1]]['t2'].isna().values[0]:
                t22 = pokemon.loc[pokemon.id == combat.iloc[i,1]]['t2'].values[0]
                if t11_atk != -1:
                    t11_atk *= df_type.loc[t11][t22]
                else:
                    t11_spatk *= df_type.loc[t11][t22]
        #compute the atk_eff & spatk_eff score
        if t11_atk != -1:
            if t12_atk != -1:
                atk_eff.append(max(t11_atk,t12_atk)/defense)
                spatk_eff.append(spatk/spdef)
            elif t12_spatk != -1:
                atk_eff.append(t11_atk/defense)
                spatk_eff.append(t12_spatk/spdef)
            else:
                atk_eff.append(t11_atk/defense)
                spatk_eff.append(spatk/spdef)
        else:
            if t12_atk != -1:
                atk_eff.append(t12_atk/defense)
                spatk_eff.append(t11_spatk/spdef)
            elif t12_spatk != -1:
                atk_eff.append(attack/defense)
                spatk_eff.append(max(t11_spatk,t12_spatk)/spdef)
            else:
                atk_eff.append(attack/defense)
                spatk_eff.append(t11_spatk/spdef)
            
    return atk_eff,spatk_eff

In [15]:
def createHpSpLegDF(pokemon,combat):
    hp_adv, speed_adv, legendary_adv = [], [], []
    for i in range(combat.shape[0]):
        hp_adv.append(pokemon[pokemon.id == combat.iloc[i,0]]['hp'].values[0] - \
                      pokemon[pokemon.id == combat.iloc[i,1]]['hp'].values[0])
        speed_diff = pokemon[pokemon.id == combat.iloc[i,0]]['speed'].values[0] - \
                     pokemon[pokemon.id == combat.iloc[i,1]]['speed'].values[0]
        if speed_diff > 0:
            speed_diff = 1
        if speed_diff < 0:
            speed_diff = -1
        speed_adv.append(speed_diff)
        legendary_adv.append(pokemon[pokemon.id == combat.iloc[i,0]]['legendary'].values[0] - \
                             pokemon[pokemon.id == combat.iloc[i,1]]['legendary'].values[0])
    
    return hp_adv, speed_adv, legendary_adv

In [16]:
def createMaxAtkDiff(pokemon,combat):
    max_diff = []
    for i in range(combat.shape[0]):
        diff_atk = pokemon[pokemon.id == combat.iloc[i,0]]['attack'].values[0] - \
                   pokemon[pokemon.id == combat.iloc[i,1]]['defense'].values[0]
        diff_spatk = pokemon[pokemon.id == combat.iloc[i,0]]['spatk'].values[0] - \
                     pokemon[pokemon.id == combat.iloc[i,1]]['spdef'].values[0]
        max_diff.append(max(diff_atk, diff_spatk))
    
    return max_diff

### Reverse the combat and create a df

In [88]:
def reverseCombat(combatDF):
    cols = list(combatDF)
    cols.insert(0, cols.pop(cols.index('Second_pokemon')))
    combat_reverse = combatDF.loc[:, cols]
    return combat_reverse

In [89]:
combat_reverse = reverseCombat(combat)
combat_reverse.head()

   Second_pokemon  First_pokemon  Winner
0             298            266     298
1             701            702     701
2             668            191     668
3             683            237     683
4             231            151     151

In [96]:
def createNewFeature(pokemon,combat,combat_reverse,df_type):
    #generate 9 new feature
    atk_eff, spatk_eff = createNewEffDF(pokemon,combat,df_type)
    def_eff, spdef_eff = createNewEffDF(pokemon,combat_reverse,df_type)
    def_eff, spdef_eff = [-val for val in def_eff], [-val for val in spdef_eff]
    hp_adv, speed_adv, legendary_adv = createHpSpLegDF(pokemon,combat)
    max_atk_diff = createMaxAtkDiff(pokemon,combat)
    max_def_lose = createMaxAtkDiff(pokemon,combat_reverse)
    max_def_lose = [-val for val in max_def_lose]
    train = pd.DataFrame({'atk_eff':atk_eff, 'spatk_eff':spatk_eff, 'def_eff':def_eff, 'spdef_eff':spdef_eff,
                          'hp_adv':hp_adv, 'speed_adv':speed_adv, 'legendary_adv':legendary_adv, 
                          'max_atk_diff':max_atk_diff, 'max_def_lose':max_def_lose})
    return train

In [19]:
train = createNewFeature(pokemon,combat,combat_reverse,df_type)
train.head()

,atk_eff,def_eff,hp_adv,legendary_adv,max_atk_diff,max_def_lose,spatk_eff,spdef_eff,speed_adv
0,1.600000,-1.400000,-20.0,0,24.0,-20.0,1.125000,-4.800000,-1.0
1,2.000000,-1.791667,0.0,0,0.0,-57.0,2.000000,-0.558140,0.0
2,0.533333,-0.882353,-20.0,0,-15.0,-20.0,0.842105,-1.190476,0.0
3,0.444444,-3.000000,-37.0,0,-20.0,-80.0,0.388889,-1.500000,-1.0
4,0.521739,-0.080000,50.0,0,-115.0,60.0,1.000000,-0.142857,1.0

In [20]:
cols_in_order = ['hp_adv', 'atk_eff', 'def_eff', 'spatk_eff', 'spdef_eff', 'speed_adv', 'max_atk_diff', 'max_def_lose', 'legendary_adv']
train = train.loc[:, cols_in_order]
train.head()

,hp_adv,atk_eff,def_eff,spatk_eff,spdef_eff,speed_adv,max_atk_diff,max_def_lose,legendary_adv
0,-20.0,1.600000,-1.400000,1.125000,-4.800000,-1.0,24.0,-20.0,0
1,0.0,2.000000,-1.791667,2.000000,-0.558140,0.0,0.0,-57.0,0
2,-20.0,0.533333,-0.882353,0.842105,-1.190476,0.0,-15.0,-20.0,0
3,-37.0,0.444444,-3.000000,0.388889,-1.500000,-1.0,-20.0,-80.0,0
4,50.0,0.521739,-0.080000,1.000000,-0.142857,1.0,-115.0,60.0,0

### Logistic Regression & Random Forest

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [23]:
def load_data(train,combat):
    test = combat.copy()
    test['Winner'] = test['First_pokemon'] == test['Winner']
    test['Winner'] = test['Winner'].replace([True,False],[1,0])
    X_train, X_test, y_train, y_test = train_test_split(
    train, test['Winner'], test_size=0.2, random_state=0)
    return X_train, X_test, y_train, y_test

In [24]:
def lr(X_train, X_test, y_train, y_test):
    model = LogisticRegression()
    model.fit(X_train, y_train)
    print("Coefficients:%s, intercept %s"%(model.coef_,model.intercept_))
    print("Residual sum of squares: %.2f"% np.mean((model.predict(X_test) - y_test) ** 2))
    print('Score: %.4f' % model.score(X_test, y_test))

In [32]:
def rf(X_train, X_test, y_train, y_test):
    model = RandomForestClassifier(n_estimators=100)
    model.fit(X_train, y_train)
    print('Score: %.4f' % model.score(X_test, y_test))
    testa = model.predict(X_test) 
    print(testa[:10])

In [26]:
X_train,X_test,y_train,y_test=load_data(train,combat)
lr(X_train,X_test,y_train,y_test)

Coefficients:[[ 6.87541244e-03  5.78197411e-01  2.92942487e-01  1.75840026e-01
   1.17329866e-01  3.00887678e+00 -2.92253393e-03 -1.13390852e-03
  -2.89385647e-01]], intercept [-0.95727431]
Residual sum of squares: 0.07
Score: 0.9343

In [33]:
X_train,X_test,y_train,y_test=load_data(train,combat)
rf(X_train,X_test,y_train,y_test)

Score: 0.9524
[0 0 1 0 0 0 0 0 1 0]

### Now each of us select a pokemon team, and use the previous model to predict result

In [48]:
team1 = [9,142,269,495,414,410]   # Yao
team2 = [498,314,608,531,727,740]  # Lin
team3 = [547,409,268,617,102,716]  # Cheng
team4 = [60,60,60,60,60,60]  # Mo
team5 = [91,91,91,91,91,91]  # Mao

In [83]:
def generateBattle(*team):
    battle = []
    for i in range(len(team)):
        for j in range(i+1,len(team)):
            battle.append(pd.DataFrame({'First_pokemon': team[i], 'Second_pokemon': team[j]}))
    return battle

In [84]:
#battle stores 10 dataframe of above possible pairs
battle = generateBattle(team1,team2,team3,team4,team5)
battle[0].head()

   First_pokemon  Second_pokemon
0              9             498
1            142             314
2            269             608
3            495             531
4            414             727

In [90]:
def createReverseBattle(battle):
    reversed_battle = []
    for item in battle:
        reversed_battle.append(reverseCombat(item))
    return reversed_battle

In [93]:
reversed_battle = createReverseBattle(battle)
reversed_battle[0].head()

   Second_pokemon  First_pokemon
0             498              9
1             314            142
2             608            269
3             531            495
4             727            414

In [106]:
#battle and reversed_battle is a list of dataframes
def generateXtest(battle, reversed_battle):
    all_df = pd.DataFrame({})
    for df,df_reverse in zip(battle,reversed_battle):
        all_df = all_df.append(createNewFeature(pokemon,df,df_reverse,df_type))
    return all_df

In [111]:
all_group1_battle = generateXtest(battle, reversed_battle)
all_group1_battle.head(5)

,atk_eff,def_eff,hp_adv,legendary_adv,max_atk_diff,max_def_lose,spatk_eff,spdef_eff,speed_adv
0,1.485714,-0.705128,8.0,0,89.0,-32.0,4.542857,-1.000000,1.0
1,1.550000,-1.467890,-55.0,0,55.0,-51.0,1.076923,-0.730769,-1.0
2,1.929412,-0.446667,40.0,0,79.0,43.0,0.633333,-1.283333,-1.0
3,2.428571,-0.695652,38.0,0,100.0,15.0,1.714286,-3.368421,-1.0
4,1.082090,-0.633333,8.0,0,78.0,7.0,0.000000,-1.872727,-1.0

In [112]:
cols_in_order = ['hp_adv', 'atk_eff', 'def_eff', 'spatk_eff', 'spdef_eff', 'speed_adv', 'max_atk_diff', 'max_def_lose', 'legendary_adv']
all_group1_battle = all_group1_battle.loc[:, cols_in_order]
all_group1_battle.head()

,hp_adv,atk_eff,def_eff,spatk_eff,spdef_eff,speed_adv,max_atk_diff,max_def_lose,legendary_adv
0,8.0,1.485714,-0.705128,4.542857,-1.000000,1.0,89.0,-32.0,0
1,-55.0,1.550000,-1.467890,1.076923,-0.730769,-1.0,55.0,-51.0,0
2,40.0,1.929412,-0.446667,0.633333,-1.283333,-1.0,79.0,43.0,0
3,38.0,2.428571,-0.695652,1.714286,-3.368421,-1.0,100.0,15.0,0
4,8.0,1.082090,-0.633333,0.000000,-1.872727,-1.0,78.0,7.0,0

### Redefine the training data, here we use all data in train df, train is global where we created early

In [114]:
def load_data_no_split(train,combat):
    test = combat.copy()
    test['Winner'] = test['First_pokemon'] == test['Winner']
    test['Winner'] = test['Winner'].replace([True,False],[1,0])
    return train, test['Winner']

In [116]:
def rf_without_ytest(X_train, X_test, y_train):
    model = RandomForestClassifier(n_estimators=100)
    model.fit(X_train, y_train)
    test_res = model.predict(X_test) 
    return test_res

In [118]:
X_train, y_train = load_data_no_split(train,combat)
test = rf_without_ytest(X_train,all_group1_battle,y_train)
print(test)

[1 0 0 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 0 0]

In [152]:
oneline = combat['First_pokemon'].append(combat['Second_pokemon'])

In [159]:
len(oneline.unique())

784